# Generated by Django 5.2.6 on 2025-09-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="business_certificate",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/business_certificates/"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="documents/cv/"),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="id_document",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/id_documents/"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="documents/photos/"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="police_clearance",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/police_clearance/"
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="qualifications",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/qualifications/"
            ),
        ),
    ]
