# Generated by Django 5.2.6 on 2025-09-30 10:24

from django.db import migrations, models
from django.utils import timezone


def clear_draft_submission_dates(apps, schema_editor):
    Consultant = apps.get_model("consultants", "Consultant")
    Consultant.objects.filter(status="draft").update(submitted_at=None)


def restore_submission_dates(apps, schema_editor):
    Consultant = apps.get_model("consultants", "Consultant")
    Consultant.objects.filter(status="draft", submitted_at__isnull=True).update(
        submitted_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0002_alter_consultant_business_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(clear_draft_submission_dates, restore_submission_dates),
    ]
