# Generated by Django 5.2.6 on 2025-09-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0003_alter_consultant_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="certificate_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultant",
            name="certificate_pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/decision_certificates/"
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="rejection_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/rejection_letters/"
            ),
        ),
        migrations.AddField(
            model_name="consultant",
            name="rejection_letter_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
