# Generated by Django 5.2.6 on 2025-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0004_consultant_certificate_generated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="certificate_expires_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
