# Generated by Django 5.2.6 on 2025-10-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0005_consultant_certificate_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="staff_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("incomplete", "Incomplete"),
                    ("vetted", "Vetted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
