# Generated by Django 5.2.6 on 2025-10-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0006_consultant_staff_comment_alter_consultant_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
