# Generated by Django 5.2.6 on 2025-10-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultant",
            name="is_seen_by_staff",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
