# Generated by Django 5.2.6 on 2025-10-13 09:28

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0010_consultant_consultant_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="delivered_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="consultant",
            constraint=models.UniqueConstraint(
                fields=("user",), name="consultants_unique_application_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="consultant",
            constraint=models.UniqueConstraint(
                fields=("id_number",), name="consultants_unique_id_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="consultant",
            constraint=models.UniqueConstraint(
                fields=("email", "nationality"),
                name="consultants_unique_email_per_nationality",
            ),
        ),
    ]
