# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
        ("consultants", "0013_consultant_certificate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="audit_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="notifications",
                to="security.auditlog",
            ),
        ),
    ]
