# Generated by Django 5.2.6 on 2025-10-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultants", "0017_fix_notification_delivered_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("incomplete", "Incomplete"),
                    ("vetted", "Vetted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consultant",
            name="submitted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
