"""Custom storage backends for static file handling.

The default ``CompressedManifestStaticFilesStorage`` raises a ``ValueError``
whenever a file referenced in templates is missing from the collected static
manifest. In containerized deployments (e.g., Render) this can happen if the
manifest becomes out-of-sync with the source static assets. To avoid user-facing
500 errors in that scenario we fall back to the original file name while
continuing to serve the compressed assets generated by WhiteNoise.
"""

from whitenoise.storage import CompressedManifestStaticFilesStorage


class LenientCompressedManifestStaticFilesStorage(CompressedManifestStaticFilesStorage):
    """Serve compressed static files without failing on manifest mismatches."""

    manifest_strict = False

