"""Custom storage backends for static file handling.

The default ``CompressedManifestStaticFilesStorage`` raises a ``ValueError``
whenever a file referenced in templates is missing from the collected static
manifest. In containerized deployments (e.g., Render) this can happen if the
manifest becomes out-of-sync with the source static assets. To avoid user-facing
500 errors in that scenario we fall back to the original file name while
continuing to serve the compressed assets generated by WhiteNoise.
"""

import logging

from whitenoise.storage import CompressedManifestStaticFilesStorage


logger = logging.getLogger(__name__)


class LenientCompressedManifestStaticFilesStorage(CompressedManifestStaticFilesStorage):
    """Serve compressed static files without failing on manifest mismatches."""

    manifest_strict = False

    def hashed_name(self, name, content=None, *args, **kwargs):
        """Gracefully handle missing files when building hashed names.

        ``CompressedManifestStaticFilesStorage`` raises ``ValueError`` if the
        requested ``name`` is absent from the collected static assets. In
        containerized or ephemeral deployments this can occasionally happen when
        ``collectstatic`` is skipped or the manifest becomes stale. Instead of
        propagating a server error, fall back to the original filename so the
        request can still be served (albeit without fingerprinting).
        """

        try:
            return super().hashed_name(name, content, *args, **kwargs)
        except ValueError:
            logger.warning(
                "Static asset %s missing from manifest; serving un-hashed name", name
            )
            return self.clean_name(name)

