# Generated by Django 5.2.6 on 2025-10-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_code",
            field=models.CharField(
                choices=[
                    ("view_consultant", "Viewed consultant"),
                    ("export_pdf", "Exported consultant PDF"),
                    ("export_bulk_pdf", "Exported bulk consultant PDF"),
                    ("export_csv", "Exported consultant CSV"),
                    ("approve_application", "Approved application"),
                    ("reject_application", "Rejected application"),
                    ("request_info", "Requested more information"),
                    ("send_analytics_report", "Sent analytics report"),
                    ("certificate_issued", "Issued consultant certificate"),
                    ("certificate_revoked", "Revoked consultant certificate"),
                    ("login_success", "Successful login"),
                    ("login_failure", "Failed login"),
                    ("upload_document", "Uploaded supporting document"),
                    ("delete_document", "Deleted supporting document"),
                ],
                max_length=64,
            ),
        ),
    ]
