# Generated by Django 5.2.6 on 2025-10-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("consultant_app", "0003_seed_certificates"),
        ("consultants", "0015_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[],
            options={
                "verbose_name": "log entry",
                "verbose_name_plural": "log entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("consultants.logentry",),
        ),
        migrations.AlterModelOptions(
            name="consultant",
            options={
                "verbose_name": "consultant",
                "verbose_name_plural": "consultants",
            },
        ),
    ]
