# Generated by Django 5.2.6 on 2025-10-08 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("view_consultant", "Viewed consultant"),
                            ("export_pdf", "Exported consultant PDF"),
                            ("export_bulk_pdf", "Exported bulk consultant PDF"),
                            ("export_csv", "Exported consultant CSV"),
                            ("approve_application", "Approved application"),
                            ("reject_application", "Rejected application"),
                            ("request_info", "Requested more information"),
                        ],
                        max_length=64,
                    ),
                ),
                ("target_object", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp", "-id"),
            },
        ),
    ]
