# Generated by ChatGPT
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auditlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLog",
        ),
    ]
