name: Django CI
on:
  push: { branches: [ "main", "develop", "feature/**" ] }
  pull_request: { branches: [ "main" ] }

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
      DJANGO_SECRET_KEY: test-secret
      PYTHONUNBUFFERED: 1

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps
        run: |
          
          pip install -r requirements.txt
          pip install pytest pytest-django
      - name: Migrate
        run: python manage.py migrate --noinput
      - name: Tests
        run: pytest -q
