name: Certificate Module CI

on:
  push:
    branches: [ main, feature/certificate-generator ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      DJANGO_SETTINGS_MODULE: backend.settings.base
      PYTHONPATH: .

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov flake8

      - name: Lint code with flake8
        run: |
          echo "🧹 Running flake8 lint..."
          flake8 apps/certificates --count --max-complexity=10 --max-line-length=120 --statistics

      - name: Run tests with coverage
        run: |
          echo "🧪 Running pytest with coverage..."
          pytest apps/certificates/tests --cov=apps/certificates --cov-report=term-missing -q
